import { homeProducts, homeStores } from "./home-fixtures";
import expanded from "./expanded.json";
import type { Catalog, Product } from "../types";
// Presentation fixtures from the owner's frozen capture. Not catalog/service data.
const image = (id: string) => `/api/reference-media/${id}`;
const product = (
  input: Partial<Product> & Pick<Product, "id" | "title" | "images">,
): Product => ({
  storeId: "kitsch",
  shippingDestinations:
    input.storeId && input.storeId !== "kitsch" ? [] : ["United States"],
  referenceNewnessRank: ["bubble-sunrise", "bare-liquid"].includes(input.id)
    ? 1
    : undefined,
  category: "Cleanse",
  price: { amount: 1400, currency: "USD" },
  rating: undefined,
  ratingCount: "",
  saleUnit: "package",
  description: "Description is not included in this reference fixture.",
  variants: [
    { id: `${input.id}-default`, label: "One size", availableQuantity: 12 },
  ],
  promotion: undefined,
  ...input,
});
export const referenceCatalog: Catalog = {
  stores: [
    {
      id: "lange-hair",
      name: "L’ange Hair",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "hanacure",
      name: "Hanacure",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "bubble-skincare",
      name: "Bubble Skincare",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "bare-minerals",
      name: "Bare Minerals",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "buffy",
      name: "Buffy",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "the-citizenry",
      name: "The Citizenry",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "true-classic",
      name: "True Classic",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },
    {
      id: "kicks-crew",
      name: "KICKS CREW",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all"],
    },

    ...homeStores,
    {
      id: "city-jeans",
      name: "City Jeans",
      logo: "",
      rating: 4.8,
      ratingCount: "3.7K",
      description: "",
      categories: ["Shop all", "Jeans"],
    },
    {
      id: "fenty-beauty",
      name: "Fenty Beauty",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all", "Makeup"],
    },
    {
      id: "juvias-place",
      name: "Juvia’s Place",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all", "Makeup"],
    },

    {
      id: "chemical-guys",
      name: "Chemical Guys",
      logo: "",
      ratingCount: "",
      description: "",
      categories: ["Shop all", "Kits", "Exterior", "Interior"],
    },
    {
      id: "jeans-warehouse",
      name: "Jeans Warehouse",
      logo: "",
      rating: 4.7,
      ratingCount: "294",
      description: "",
      categories: ["Shop all", "Jeans"],
    },
    {
      id: "fork",
      name: "FORK Eyewear",
      logo: "",
      rating: 4.6,
      ratingCount: "293",
      categories: ["Shop all", "Sunglasses"],
      description: "",
    },
    {
      id: "akira",
      name: "AKIRA",
      logo: "",
      rating: 4.7,
      ratingCount: "121.1K",
      categories: ["Shop all", "Sunglasses"],
      description: "",
    },
    {
      id: "fitjeans",
      name: "FITJEANS",
      logo: "",
      rating: 4.6,
      ratingCount: "3.4K",
      categories: ["Shop all", "Jeans"],
      description: "",
    },
    {
      id: "miss-me",
      name: "Miss Me",
      logo: "",
      rating: 4.7,
      ratingCount: "11.9K",
      categories: ["Shop all", "Jeans"],
      description: "",
    },
    {
      id: "arrow-twenty-two",
      name: "Arrow Twenty Two",
      logo: "",
      coverImage: image("search-filter-arrow-store"),
      rating: 4.7,
      ratingCount: "7K",
      categories: ["Shop all", "Jeans"],
      description: "Captured filtered-search merchant card.",
    },
    {
      id: "american-blues",
      name: "American Blues",
      logo: "",
      coverImage: image("search-filter-american-store"),
      rating: 4.4,
      ratingCount: "11.1K",
      categories: ["Shop all", "Jeans"],
      description: "Captured filtered-search merchant card.",
    },
    {
      id: "lusoophy",
      name: "Lusoophy",
      logo: image("search-filter-lusoophy"),
      ratingCount: "",
      categories: ["Shop all", "Jeans"],
      description: "",
    },
    {
      id: "givenchy",
      name: "Givenchy",
      logo: "",
      ratingCount: "",
      categories: ["Shop all", "Jeans"],
      description: "",
    },
    {
      id: "kitsch",
      name: "KITSCH",
      logo: image("kitsch-logo"),
      coverImage: image("rice-bundle"),
      rating: 4.5,
      ratingCount: "194.9K",
      categories: ["Shop all", "Cleanse", "Heatless Hair", "What's New"],
      description:
        "Elevating your everyday essentials, KITSCH is a US designed brand worn & loved by your favorite celebrities. Shop online for free shipping on orders.",
    },
    {
      id: "vehla",
      name: "VEHLA",
      logo: image("vehla-logo"),
      rating: 4.2,
      ratingCount: "2.1K",
      categories: ["Shop all", "Sunglasses"],
      description: "Eyewear for every day.",
    },
    {
      id: "pura",
      name: "Pura",
      logo: image("pura-logo"),
      rating: 4.8,
      ratingCount: "1M",
      categories: ["Shop all", "Fragrance"],
      description: "Your home, your fragrance.",
    },
    {
      id: "fashion-nova",
      name: "Fashion Nova",
      logo: image("fashion-logo"),
      rating: 4.3,
      ratingCount: "428.8K",
      categories: ["Shop all", "Jeans"],
      description: "Find your next favorite fit.",
    },
    {
      id: "origin",
      name: "ORIGIN",
      logo: image("origin-logo"),
      rating: 4.7,
      ratingCount: "11.9K",
      categories: ["Shop all", "Jeans"],
      description: "Everyday denim and essentials.",
    },
  ],
  products: [
    // Flow 10 / 002 exposes the Jojoba title and $14.00 beneath the translucent
    // dock. The original photograph is already provenance-verified. Ratings,
    // detailed description and real inventory are not supplied by that frame.
    product({
      id: "idea-jojoba",
      title: "Jojoba Bead Exfoliating Body Wash Bar",
      images: [image("idea-jojoba")],
      price: { amount: 1400, currency: "USD" },
    }),
    // Title/price from frozen collection flow 11 / 002. The full liquid-pair
    // original is independently recorded in product-media-provenance.json.
    product({
      id: "argan-liquid-combo",
      title: "Repairing Argan Oil Shampoo & Conditioner Combo",
      images: [image("argan-liquid-combo")],
      price: { amount: 2800, currency: "USD" },
    }),

    product({
      id: "detox-shampoo",
      title: "Detox Shampoo Bar",
      images: [image("detox-shampoo")],
      price: { amount: 1600, currency: "USD" },
      ratingCount: "10",
    }),
    product({
      id: "rice-liquid",
      title: "Rice Water Shampoo for Hair Growth",
      images: [image("rice-liquid")],
      price: { amount: 1400, currency: "USD" },
      ratingCount: "92",
    }),
    product({
      id: "rosemary-liquid",
      title: "Rosemary & Biotin Volumizing Shampoo",
      images: [image("rosemary-liquid")],
      price: { amount: 1600, currency: "USD" },
      ratingCount: "91",
    }),
    product({
      id: "rosemary-bar",
      title: "Rosemary & Biotin Volumizing Shampoo Bar",
      images: [image("rosemary-bar")],
      price: { amount: 1600, currency: "USD" },
    }),

    product({
      id: "assistant-urban-straight",
      storeId: "jeans-warehouse",
      title: "URBAN STRAIGHT DENI…",
      category: "Jeans",
      images: [image("assistant-black")],
      price: { amount: 2699, currency: "USD" },
    }),
    product({
      id: "summer-mystery-box",
      sourceNewestRank: 0,
      title: "Summer Mystery Box",
      storeId: "kitsch",
      category: "What's New",
      images: ["/api/reference-media/summer-tight"],
      price: { amount: 7200, currency: "USD" },
      ratingCount: "7",
      compareAt: { amount: 13500, currency: "USD" },
      promotion: "47% off",
    }),
    product({
      id: "chemical-clean-trim",
      title: "Clean Trim and Dash...",
      storeId: "chemical-guys",
      category: "Kits",
      images: ["/api/reference-media/chemical-card1"],
      price: { amount: 2999, currency: "USD" },
      ratingCount: "",
      compareAt: { amount: 3397, currency: "USD" },
      promotion: "12% off",
    }),
    product({
      id: "chemical-easy-clean",
      title: "Easy Clean & Protect...",
      storeId: "chemical-guys",
      category: "Kits",
      images: ["/api/reference-media/chemical-card2"],
      price: { amount: 5099, currency: "USD" },
      ratingCount: "",
      compareAt: { amount: 5599, currency: "USD" },
      promotion: "9% off",
    }),
    product({
      id: "assistant-signature-straight",
      title: "SIGNATURE STRAIGHT...",
      storeId: "jeans-warehouse",
      category: "Jeans",
      images: ["/api/reference-media/assistant-white"],
      price: { amount: 2999, currency: "USD" },
      ratingCount: "",
    }),
    product({
      id: "beachy-gelato",
      sourceNewestRank: 1,
      title: "Beachy Gelato Hair & Body Perfume Mist",
      category: "What's New",
      images: [image("beachy-gelato")],
      price: { amount: 2000, currency: "USD" },
      ratingCount: "108",
    }),
    ...(expanded.map((p) => ({
      ...p,
      referenceNewnessRank: ["bubble-sunrise", "bare-liquid"].includes(p.id)
        ? 1
        : undefined,
      ratingCount: p.ratingCount ?? "",
      promotion: p.promotion ?? undefined,
      compareAt: p.compareAt ?? undefined,
      price: { ...p.price, currency: "USD" as const },
      saleUnit: "piece" as const,
    })) as Product[]),
    product({
      id: "rice-bundle",
      ratingCount: "4.8K",
      title: "Rice Water Shampoo & Conditioner Combo",
      images: [image("rice-bundle")],
      price: { amount: 2800, currency: "USD" },
    }),
    product({
      id: "shea-butter",
      rating: 4.6,
      ratingCount: "3.3K",
      title: "Shea Butter Exfoliating Body Wash",
      images: [image("shea"), image("shea-detail"), image("shea-photo")],
      price: { amount: 1400, currency: "USD" },
    }),
    product({
      id: "shampoo-bag",
      title: "Shampoo Bar Bag",
      images: [image("shampoo-bag")],
      price: { amount: 500, currency: "USD" },
      rating: 4.6,
      ratingCount: "3.8K",
    }),
    product({
      id: "rice-shampoo",
      ratingCount: "13.7K",
      title: "Rice Water Shampoo Bar for Hair Growth",
      images: [image("rice-shampoo")],
      price: { amount: 1600, currency: "USD" },
    }),
    product({
      id: "rice-conditioner",
      title: "Rice Water Conditioner Bar",
      images: [image("rice-conditioner")],
      price: { amount: 1600, currency: "USD" },
      ratingCount: "10.2K",
    }),
    product({
      id: "terracotta",
      title: "Terracotta Self-Draining Shampoo Bar Holder",
      images: [image("terracotta")],
      price: { amount: 1600, currency: "USD" },
      ratingCount: "2.9K",
    }),
    product({
      id: "rosemary",
      title: "Rosemary & Biotin Volumizing Shampoo Bar",
      images: [image("rosemary")],
      price: { amount: 1400, currency: "USD" },
      ratingCount: "6.1K",
    }),
    product({
      id: "cleo",
      title: "Cleo - Black/Smoke",
      images: [image("cleo")],
      storeId: "vehla",
      category: "Sunglasses",
      price: { amount: 25000, currency: "USD" },
      rating: 4.5,
      ratingCount: "54",
      promotion: undefined,
    }),
    product({
      id: "round-sunglasses",
      title: "HUSH - Silver / Blue",
      images: [image("round-sunglasses")],
      storeId: "fork",
      category: "Sunglasses",
      price: { amount: 9500, currency: "USD" },
      rating: 4.9,
      ratingCount: "10",
      description: "Round metal frame with a double rim.",
      saleUnit: "piece",
    }),
    product({
      id: "u-see-me",
      title: "U SEE ME GLASSES",
      images: [image("u-see-me")],
      storeId: "akira",
      category: "Sunglasses",
      price: { amount: 1490, currency: "USD" },
      rating: 4.7,
      ratingCount: "6",
      description: "Oval glasses with rimless clear lenses.",
      saleUnit: "piece",
      promotion: undefined,
    }),
    product({
      id: "carpenter-jeans",
      title: "Contrast Lining Carpenter Straight Jeans - Black",
      images: [image("carpenter-jeans")],
      storeId: "fashion-nova",
      category: "Jeans",
      color: "Black",
      country: "United States",
      price: { amount: 3499, currency: "USD" },
      rating: 5,
      ratingCount: "24",
      promotion: undefined,
      variants: [
        { id: "carpenter-xs", label: "XS", availableQuantity: 0 },
        { id: "carpenter-s", label: "S", availableQuantity: 5 },
        { id: "carpenter-m", label: "M", availableQuantity: 7 },
        { id: "carpenter-l", label: "L", availableQuantity: 4 },
      ],
    }),
    product({
      id: "valentino-blue-denim",
      title: "Valentino Blue Denim - Straight-Leg Jeans Women",
      images: [image("search-filter-valentino")],
      storeId: "lusoophy",
      category: "Jeans",
      gender: "Women",
      price: { amount: 206100, currency: "USD" },
      compareAt: { amount: 309800, currency: "USD" },
      ratingCount: "",
      promotion: "Save $130",
      description:
        "Captured filtered-search result; a complete description was not included.",
      saleUnit: "piece",
      variants: [
        {
          id: "valentino-blue-denim-reference",
          label: "Reference only",
          availableQuantity: 0,
        },
      ],
    }),
    product({
      id: "givenchy-wide-leg-denim",
      title: "Givenchy Wide-leg denim cotton jeans",
      images: [image("search-filter-givenchy")],
      storeId: "givenchy",
      category: "Jeans",
      gender: "Women",
      price: { amount: 129300, currency: "USD" },
      compareAt: { amount: 149600, currency: "USD" },
      ratingCount: "",
      promotion: "Save $65",
      description:
        "Captured filtered-search result; a complete description was not included.",
      saleUnit: "piece",
      variants: [
        {
          id: "givenchy-wide-leg-reference",
          label: "Reference only",
          availableQuantity: 0,
        },
      ],
    }),
    product({
      id: "heritage-jeans",
      title: "HERITAGE COTTON JEANS",
      images: [image("heritage-jeans")],
      storeId: "origin",
      category: "Jeans",
      color: "Black",
      country: "United States",
      price: { amount: 7600, currency: "USD" },
      compareAt: { amount: 8800, currency: "USD" },
      rating: 5,
      ratingCount: "164",
      promotion: "Save $40",
    }),
    product({
      id: "black-conditioner-bag",
      title: "Black Conditioner Bar Bag",
      images: [image("black-conditioner-bag")],
      price: { amount: 600, currency: "USD" },
    }),
    product({
      id: "chocolate-body-bag",
      title: "Chocolate Body Wash Bag",
      images: [image("chocolate-body-bag")],
      price: { amount: 500, currency: "USD" },
    }),
    product({
      id: "shower-caddy",
      title: "Self-Draining Shower Caddy",
      images: [image("shower-caddy")],
      price: { amount: 4000, currency: "USD" },
      compareAt: { amount: 7500, currency: "USD" },
    }),
    product({
      id: "solid-shave-butter",
      title: "Solid Shave Butter",
      images: [image("solid-shave-butter")],
      price: { amount: 1000, currency: "USD" },
    }),
    product({
      id: "sugar-body-scrub",
      title: "Exfoliating Sugar Body Scrub",
      images: [image("sugar-body-scrub")],
      price: { amount: 1200, currency: "USD" },
      ratingCount: "2.4K",
    }),
    product({
      id: "charcoal-body-wash",
      title: "Charcoal Detoxifying Solid Body Wash",
      images: [image("charcoal-body-wash")],
      price: { amount: 1400, currency: "USD" },
      rating: 4.8,
      ratingCount: "984",
    }),
    ...homeProducts,
  ],
};
